"use client";

import { useEffect, useRef, useState } from "react";
import AppSidebar from "@/app/components/AppSidebar";
import SyncTabs from "../SyncTabs";

interface Row {
  leadId: string;
  name: string;
  phone: string;
  category: string;
  categoryLabel: string;
  suggestedStage: "Prospect" | "Contacted" | "Demo" | "Lost" | null;
  // Written by hand (a human or a Claude Code session reading the day's WA
  // chat directly) into sync_daily_summaries — not generated by this page
  // or any API call it makes. See schema.prisma's SyncDailySummary doc
  // comment: the rep decided 2026-10-01 a paid Anthropic API key for an
  // in-app button wasn't worth it when a Claude Code session already doing
  // this work can just write the row. Null until someone has.
  claudeSummary: string | null;
}

interface DailyLogResponse {
  date: string;
  count: number;
  rows: Row[];
}

const STAGE_COLORS: Record<string, string> = {
  Prospect: "#64748b",
  Contacted: "#0ea5e9",
  Demo: "#8b5cf6",
  Lost: "#dc2626",
};

function todayWibString(): string {
  const now = new Date();
  const wib = new Date(now.getTime() + 7 * 60 * 60 * 1000);
  return wib.toISOString().slice(0, 10);
}

// v3: per-lead console feedback added (v2 = notes + stage in one script). Old keys
// hold the older, quiet scripts — a stale one would hide the new logging.
function scriptStorageKey(date: string) {
  return `sync-dailylog-script-v3-${date}`;
}

const CRM_STAGE_VALUE: Record<string, string> = {
  Prospect: "prospek",
  Contacted: "kontak",
  Demo: "demo",
  Lost: "batal",
};

function normPhoneJsSnippet(): string {
  return `function normPhone(p) {
  if (!p) return "";
  let d = String(p).replace(/\\D/g, "");
  if (d.startsWith("62")) d = "0" + d.slice(2);
  if (d.startsWith("8")) d = "0" + d;
  return d;
}`;
}

// One line per lead, so `updateEntryBody` below can find-and-replace a
// single line without disturbing anything else the rep hand-edited —
// e.g. changing "kind" to "meeting" for one lead, changing "want" (target
// stage; "" = leave the stage alone), deleting a lead they don't want to
// log, or reordering. This whole block is meant to be edited as plain text
// (same habit as scripts/crm-sync/crm-team-sync.js's MY_LEADS array), not
// just generated once and pasted verbatim.
function entryLine(name: string, phone: string, kind: string, body: string, want: string): string {
  return `  { name: ${JSON.stringify(name)}, norm_phone: ${JSON.stringify(phone)}, kind: ${JSON.stringify(kind)}, body: ${JSON.stringify(body)}, want: ${JSON.stringify(want)} },`;
}

// One script, two steps per lead (merged 2026-10-01 from the separate
// /sync/dailylog/test note-logging script and /sync/dailylog/stage/apply
// stage script, both of which were verified live against the real CRM):
//   1. note: POST /api/leads/{id}/activities with outcome "outbound" (the
//      form's own default, confirmed 2026-09-30). Skipped when body is
//      empty, and when an identical body already shows in that lead's
//      activities (the endpoint has no dedupe of its own, so re-running the
//      script would otherwise double-log).
//   2. stage: PATCH /api/leads/{id} {stage}, using the suggested stage from
//      crmStageMapping.ts. Raise-only (prospek < kontak < demo < uji_coba <
//      konversi); never lowers, never overwrites "batal", and "batal" is
//      only set from prospek/kontak — the anti-downgrade rule from
//      Context/CRMSync/0.CRMSahaibatUnderstanding.md.
// `kind` defaults to "whatsapp"; hand-edit it for a lead you called, met or
// emailed instead. `body` starts pre-filled from that lead's Ringkasan
// Claude when one exists.
function buildTemplate(date: string, rows: Row[]): string {
  const entriesLiteral = rows
    .map((r) =>
      entryLine(r.name, r.phone, "whatsapp", r.claudeSummary ?? "", r.suggestedStage ? CRM_STAGE_VALUE[r.suggestedStage] : ""),
    )
    .join("\n");

  return `/**
 * DAILY LOG + STAGE SYNC — ${date}. Edit "body" / "kind" / "want" per lead,
 * then paste this WHOLE block into DevTools Console on sales.sahaibat.com
 * (must be logged in), on any page.
 *
 * Per lead: (1) logs the note via POST /api/leads/{id}/activities (skipped
 * if body is empty or the same text is already logged), then (2) raises the
 * stage via PATCH /api/leads/{id} to "want" ("" = leave stage alone). Stage
 * only goes UP (prospek < kontak < demo < uji_coba < konversi); a lead at
 * "batal" is never overwritten; "batal" is only set from prospek/kontak.
 *
 * APPLY = false is a dry run: prints what would happen, changes nothing.
 */
const APPLY = true;

const ENTRIES = [
${entriesLiteral}
];

const RANK = { prospek: 1, kontak: 2, demo: 3, uji_coba: 4, konversi: 5 };

${normPhoneJsSnippet()}

async function getActivities(id) {
  try {
    const r = await fetch(\`/api/leads/\${id}/activities\`, { credentials: "include", cache: "no-store" });
    if (!r.ok) return null;
    return await r.json();
  } catch {
    return null;
  }
}

function hasBody(activities, body) {
  return activities != null && JSON.stringify(activities).includes(JSON.stringify(body).slice(1, -1));
}

function short(v) {
  const s = typeof v === "string" ? v : JSON.stringify(v);
  return s && s.length > 160 ? s.slice(0, 160) + "…" : s;
}

async function run() {
  console.log(\`=== Mulai (\${APPLY ? "APPLY" : "DRY RUN"}): \${ENTRIES.length} lead, \${ENTRIES.filter((e) => e.body.trim()).length} dengan note ===\`);
  const leadsRes = await fetch("/api/leads", { credentials: "include", cache: "no-store" });
  console.log("GET /api/leads ->", leadsRes.status);
  const leadsData = await leadsRes.json();
  const leadsArr = leadsData.leads || leadsData;
  console.log("Lead di CRM tim:", leadsArr.length);

  const rep = { notFound: [], noteLogged: [], noteDuplicate: [], noteFailed: [], stageChanged: [], stageSkipped: [], stageFailed: [] };
  let n = 0;

  for (const e of ENTRIES) {
    n++;
    const tag = \`[\${n}/\${ENTRIES.length}] \${e.name}\`;
    const lead = leadsArr.find((x) => normPhone(x.phone) === e.norm_phone);
    if (!lead) {
      console.warn(\`\${tag} — ❌ TIDAK DITEMUKAN di CRM tim (telepon \${e.norm_phone})\`);
      rep.notFound.push(e.name);
      continue;
    }

    // 1) NOTE
    if (!e.body.trim()) {
      console.log(\`\${tag} — note: dilewati (body kosong)\`);
    } else {
      const before = await getActivities(lead.id);
      if (hasBody(before, e.body)) {
        console.log(\`\${tag} — note: ⏭ sudah ada di CRM, tidak dicatat ulang\`);
        rep.noteDuplicate.push(e.name);
      } else if (!APPLY) {
        console.log(\`\${tag} — note: (dry run) akan dicatat [\${e.kind}]: \${e.body}\`);
        rep.noteLogged.push(e.name + " (dry run)");
      } else {
        const res = await fetch(\`/api/leads/\${lead.id}/activities\`, {
          method: "POST",
          credentials: "include",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ kind: e.kind, body: e.body, outcome: "outbound" }),
        });
        const resBody = await res.json().catch(() => null);
        if (res.ok) {
          const after = await getActivities(lead.id);
          const verified = hasBody(after, e.body);
          console.log(\`\${tag} — note: ✅ BERHASIL dicatat [\${e.kind}] (HTTP \${res.status}, \${verified ? "terverifikasi muncul di aktivitas" : "⚠ belum terlihat di aktivitas"}): \${e.body}\`, resBody);
          rep.noteLogged.push(e.name);
        } else {
          console.error(\`\${tag} — note: ❌ GAGAL HTTP \${res.status}\`, resBody);
          rep.noteFailed.push({ name: e.name, status: res.status, response: short(resBody) });
        }
      }
    }

    // 2) STAGE
    if (!e.want) {
      console.log(\`\${tag} — stage: dilewati (want kosong)\`);
      continue;
    }
    const cur = lead.stage;
    let why = null;
    if (cur === e.want) why = "sudah " + cur;
    else if (cur === "batal") why = "sekarang Lost (batal), tidak ditimpa";
    else if (e.want === "batal") {
      if (RANK[cur] > 2) why = "ingin Lost tapi sekarang " + cur;
    } else if (!(RANK[e.want] > RANK[cur])) why = "tidak diturunkan: " + cur + " -> " + e.want;
    if (why) {
      console.log(\`\${tag} — stage: ⏭ dilewati (\${why})\`);
      rep.stageSkipped.push({ name: e.name, why });
      continue;
    }
    if (!APPLY) {
      console.log(\`\${tag} — stage: (dry run) akan diubah \${cur} -> \${e.want}\`);
      rep.stageChanged.push(e.name + ": " + cur + " -> " + e.want + " (dry run)");
      continue;
    }
    const sres = await fetch(\`/api/leads/\${lead.id}\`, {
      method: "PATCH",
      credentials: "include",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ stage: e.want }),
    });
    const sBody = await sres.json().catch(() => null);
    if (sres.ok) {
      const nowStage = sBody && (sBody.lead ? sBody.lead.stage : sBody.stage);
      console.log(\`\${tag} — stage: ✅ BERHASIL \${cur} -> \${e.want} (HTTP \${sres.status}\${nowStage ? ", server kini: " + nowStage : ""})\`, sBody);
      rep.stageChanged.push(e.name + ": " + cur + " -> " + e.want);
    } else {
      console.error(\`\${tag} — stage: ❌ GAGAL \${cur} -> \${e.want} HTTP \${sres.status}\`, sBody);
      rep.stageFailed.push({ name: e.name, status: sres.status, response: short(sBody) });
    }
  }

  console.log("=== RINGKASAN (" + (APPLY ? "APPLY" : "DRY RUN") + ") ===");
  console.log(\`Tidak ditemukan di CRM: \${rep.notFound.length}\`, rep.notFound);
  console.log(\`Note tercatat: \${rep.noteLogged.length}\`, rep.noteLogged);
  console.log(\`Note dilewati (sudah ada): \${rep.noteDuplicate.length}\`, rep.noteDuplicate);
  console.log(\`Note gagal: \${rep.noteFailed.length}\`, rep.noteFailed);
  console.log(\`Stage berubah: \${rep.stageChanged.length}\`, rep.stageChanged);
  console.log(\`Stage dilewati: \${rep.stageSkipped.length}\`, rep.stageSkipped);
  console.log(\`Stage gagal: \${rep.stageFailed.length}\`, rep.stageFailed);
  return rep;
}

run().catch((err) => console.error("SCRIPT ERROR:", err));
`;
}

// Finds the line for `phone` (matched on its exact norm_phone literal) and
// swaps in a new body — leaves every other line, and any manual edits on
// them, untouched.
function updateEntryBody(scriptText: string, phone: string, newBody: string): string {
  const needle = `norm_phone: ${JSON.stringify(phone)}`;
  return scriptText
    .split("\n")
    .map((line) => {
      if (!line.includes(needle)) return line;
      return line.replace(/body: "(?:[^"\\]|\\.)*"/, `body: ${JSON.stringify(newBody)}`);
    })
    .join("\n");
}

export default function DailyLogPage() {
  const [date, setDate] = useState(todayWibString());
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [script, setScript] = useState("");
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const scriptRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/sync/dailylog?date=${date}`)
      .then((r) => r.json())
      .then((d: DailyLogResponse) => {
        setRows(d.rows);
        let saved: string | null = null;
        try {
          saved = window.localStorage.getItem(scriptStorageKey(date));
        } catch {
          // localStorage unavailable — just fall through to a fresh template.
        }
        setScript(saved ?? buildTemplate(date, d.rows));
      })
      .finally(() => setLoading(false));
  }, [date]);

  function updateScript(next: string) {
    setScript(next);
    try {
      window.localStorage.setItem(scriptStorageKey(date), next);
    } catch {
      // per-viewer convenience only — edits just won't survive a refresh.
    }
  }

  function resetTemplate() {
    updateScript(buildTemplate(date, rows));
    setCopied(false);
  }

  function useSummary(row: Row) {
    if (!row.claudeSummary) return;
    updateScript(updateEntryBody(script, row.phone, row.claudeSummary));
  }

  // navigator.clipboard needs a secure context (HTTPS or localhost) — this
  // app is served plain HTTP on the VPS's bare IP (http://103.93.162.31:3000,
  // no domain/TLS set up), where that API is simply absent, so the old
  // clipboard.writeText-only version failed silently every time. Falls back
  // to the older select()+execCommand("copy") approach, which works over
  // plain HTTP, instead of leaving the user with a button that does nothing.
  async function copyScript() {
    setCopyError(false);
    if (navigator.clipboard && window.isSecureContext) {
      try {
        await navigator.clipboard.writeText(script);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        return;
      } catch {
        // fall through to the legacy path below
      }
    }
    const el = scriptRef.current;
    if (!el) {
      setCopyError(true);
      return;
    }
    el.focus();
    el.select();
    let ok = false;
    try {
      ok = document.execCommand("copy");
    } catch {
      ok = false;
    }
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } else {
      // Last resort: text is already selected in the textarea above —
      // tell the user to copy it themselves rather than pretend it worked.
      setCopyError(true);
    }
  }

  return (
    <div className="flex h-screen overflow-hidden bg-[#f7f8fa] text-slate-900">
      <AppSidebar active="sync" />
      <div className="flex-1 overflow-y-auto p-6">
        <h1 className="mb-1 text-lg font-bold text-slate-900">CRM Sync</h1>
        <p className="mb-4 text-sm text-slate-500">
          Lead yang dichat pada tanggal terpilih — satu script untuk catat note + naikkan stage. Edit teks di bawah, lalu paste ke console sales.sahaibat.com.
        </p>
        <SyncTabs />

        <div className="mb-4 flex items-center gap-3">
          <label className="text-sm font-medium text-slate-600">
            Tanggal
            <input
              type="date"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              className="ml-2 rounded-lg border border-slate-300 px-2 py-1 text-sm"
            />
          </label>
          {!loading && <span className="text-sm text-slate-500">{rows.length} lead dichat tanggal ini</span>}
        </div>

        {loading && <div className="text-sm text-slate-400">Memuat…</div>}

        {!loading && rows.length === 0 && (
          <div className="rounded-xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-500">
            Tidak ada aktivitas WA pada tanggal ini.
          </div>
        )}

        {!loading && rows.length > 0 && (
          <>
            <div className="mb-2 flex items-center justify-between">
              <div className="text-sm font-semibold text-slate-700">
                Script — edit &quot;body&quot; tiap lead, lalu paste ke DevTools Console di sales.sahaibat.com
              </div>
              <div className="flex gap-2">
                <button
                  onClick={resetTemplate}
                  className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-600 hover:bg-slate-50"
                  title="Buang semua editan, mulai ulang dari template kosong"
                >
                  Reset ke template
                </button>
                <button
                  onClick={copyScript}
                  className="rounded-lg bg-cyan-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-cyan-700"
                >
                  {copied ? "Tersalin ✓" : "Copy script"}
                </button>
              </div>
            </div>
            {copyError && (
              <div className="mb-2 text-xs text-amber-600">
                Tidak bisa copy otomatis di browser ini — teksnya sudah ke-select di bawah, tekan Ctrl+C (atau Cmd+C) manual.
              </div>
            )}
            <textarea
              ref={scriptRef}
              value={script}
              onChange={(e) => updateScript(e.target.value)}
              spellCheck={false}
              rows={18}
              className="mb-6 w-full rounded-xl border border-slate-300 bg-slate-900 p-3 font-mono text-xs text-slate-100"
            />

            <div className="text-sm font-semibold text-slate-700">
              Referensi lead ({rows.length}) — kolom &quot;Ringkasan Claude&quot; diisi manual (lihat Context/CRMSync),
              klik &quot;Pakai&quot; buat nyuntik ke baris lead itu di script di atas
            </div>
            <div className="mt-2 overflow-hidden rounded-xl border border-slate-200 bg-white">
              <table className="w-full text-sm">
                <thead className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500">
                  <tr>
                    <th className="px-3 py-2">Lead</th>
                    <th className="px-3 py-2">Label</th>
                    <th className="px-3 py-2 w-full">Ringkasan Claude</th>
                    <th className="px-3 py-2" />
                  </tr>
                </thead>
                <tbody>
                  {rows.map((r) => (
                    <tr key={r.leadId} className="border-t border-slate-100 align-top">
                      <td className="px-3 py-2">
                        <div className="font-medium text-slate-800">{r.name}</div>
                        <div className="text-xs text-slate-400">{r.phone}</div>
                      </td>
                      <td className="px-3 py-2">
                        <div className="text-xs text-slate-500">{r.categoryLabel}</div>
                        {r.suggestedStage && (
                          <div
                            className="mt-1 inline-block rounded-full px-2 py-0.5 text-[11px] font-semibold text-white"
                            style={{ background: STAGE_COLORS[r.suggestedStage] }}
                          >
                            → {r.suggestedStage}
                          </div>
                        )}
                      </td>
                      <td className="px-3 py-2 text-slate-600">
                        {r.claudeSummary || <span className="text-slate-300">— belum diringkas —</span>}
                      </td>
                      <td className="px-3 py-2 text-right">
                        <button
                          onClick={() => useSummary(r)}
                          disabled={!r.claudeSummary}
                          className="whitespace-nowrap rounded-lg border border-cyan-600 px-2 py-1 text-xs font-medium text-cyan-700 hover:bg-cyan-50 disabled:opacity-30"
                        >
                          Pakai →
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
