import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { classifyLead, categoryLabels, type LeadCategory } from "@/lib/leadSegmentation";
import { getNoReplyAfterPitchContactIds } from "@/lib/noReplyAfterPitch";
import { getNonResponsiveContactIds } from "@/lib/nonResponsive";
import { CATEGORY_TO_CRM_STAGE } from "@/lib/crmStageMapping";
import { wibDayRange, todayWib } from "@/lib/syncDateRange";

/**
 * Backs /sync/dailylog — "which leads did I actually chat with today, what
 * are they tagged, and what should I log for them in sales.sahaibat.com's
 * Activity form". One row per lead with any wa_messages activity that day
 * (either direction, same as the SOP's "wa-chat-today" query — see
 * Context/2.LeadPipelineScripts.md), enriched with the SAME classifyLead()
 * tag every other page in this app uses (so the suggested label here can
 * never disagree with /chat or /reports), mapped to a suggested CRM-tim
 * stage per Context/CRMSync/0.CRMSahaibatUnderstanding.md's Goal 1 table.
 *
 * The suggested stage is advisory only — this route never writes to
 * sales.sahaibat.com. The page turns edited rows into a copy-pasteable
 * console script (same pattern as scripts/crm-sync/crm-team-sync.js) that
 * the rep runs there themselves.
 *
 * `claudeSummary` is read-only here — see SyncDailySummary in schema.prisma
 * for who writes it (a human/Claude-Code session, by hand, not this app).
 */
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const date = searchParams.get("date") || todayWib();
  const { start, end } = wibDayRange(date);

  const [contacts, noReplyAfterPitchIds, nonResponsiveIds, summaries] = await Promise.all([
    db.waContact.findMany({
      where: {
        leadId: { not: null },
        messages: { some: { sentAt: { gte: start, lte: end } } },
      },
      select: {
        id: true,
        noWaAccount: true,
        appointment: true,
        declined: true,
        needsOtherContact: true,
        needsFollowUp: true,
        letterSent: true,
        repliedOverrideAt: true,
        repliedOverrideKind: true,
        messages: { orderBy: { sentAt: "desc" }, take: 1, select: { direction: true, sentAt: true } },
        lead: { select: { id: true, name: true, phoneNormalized: true, pipelineStage: true } },
      },
    }),
    getNoReplyAfterPitchContactIds(),
    getNonResponsiveContactIds(),
    // Written by hand (see SyncDailySummary's doc comment in schema.prisma)
    // — not generated by this route, just read back here if someone already
    // wrote one for this date.
    db.syncDailySummary.findMany({ where: { date }, select: { leadId: true, summary: true } }),
  ]);
  const summaryByLeadId = new Map(summaries.map((s) => [s.leadId, s.summary]));

  // A lead can have more than one wa_contacts row; classifyLead wants ALL
  // of them together (its OR-across-contacts logic — see leadSegmentation.ts)
  // so group by lead before classifying, same shape /api/leads uses.
  const byLead = new Map<string, { name: string; phone: string | null; contacts: typeof contacts }>();
  for (const c of contacts) {
    if (!c.lead) continue;
    const entry = byLead.get(c.lead.id) ?? { name: c.lead.name, phone: c.lead.phoneNormalized, contacts: [] };
    entry.contacts.push(c);
    byLead.set(c.lead.id, entry);
  }

  const labels = categoryLabels("id");
  const rows = [...byLead.entries()]
    .map(([leadId, { name, phone, contacts: leadContacts }]) => {
      const category: LeadCategory = classifyLead({
        pipelineStage: "contacted", // irrelevant here — every lead in this set has >=1 wa_contacts row today, so it can never be "untouched"
        contacts: leadContacts.map((c) => ({
          noWaAccount: c.noWaAccount,
          appointment: c.appointment,
          declined: c.declined,
          needsOtherContact: c.needsOtherContact,
          needsFollowUp: c.needsFollowUp,
          letterSent: c.letterSent,
          repliedOverrideAt: c.repliedOverrideAt,
          repliedOverrideKind: c.repliedOverrideKind,
          lastMessage: c.messages[0] ?? null,
          noReplyAfterPitch: noReplyAfterPitchIds.has(c.id),
          nonResponsive: nonResponsiveIds.has(c.id),
        })),
      });
      return {
        leadId,
        name,
        phone: (phone || "").replace("+62", "0"),
        category,
        categoryLabel: labels[category],
        suggestedStage: CATEGORY_TO_CRM_STAGE[category],
        claudeSummary: summaryByLeadId.get(leadId) ?? null,
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  return NextResponse.json({ date, count: rows.length, rows });
}
